version: '3'

networks:
  public:
    driver: bridge
  private:
    driver: bridge

services:

  nginx:
    container_name: nginx_1
    build: ./nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
    tty: true
    depends_on:
      - php-fpm
    networks:
      - public
      - private

  php-fpm:
    container_name: php_1
    build: ./php-fpm
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    networks:
      - private

  mysql:
    container_name: mysql_1
    build: ./mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    networks:
      - private

  phpmyadmin:
    container_name: phpmyadmin_1
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_HOST=mysql
    networks:
      - public
      - private

  composer:
    container_name: composer_1
    image: composer/composer:alpine
    volumes:
      - ${COMPOSER_EXEC_PATH}:/app
